name: integrationTests

on:
  push:

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Before script
        run: |
          chmod +x gradlew
          chmod +x publishAllToMavenLocal.sh

      - name: Run Gradle command
        run: |
          bash ./publishAllToMavenLocal.sh
          ./gradlew :demo:test

